import { HabitatDesign, HabitatShape, ModuleType, Destination, LaunchVehicle } from '../types/habitat';

/**
 * Sample habitat designs to demonstrate the application capabilities
 */

// Sample 1: Luna Base Alpha - Lunar Surface Habitat
export const LUNA_BASE_ALPHA: HabitatDesign = {
  id: 'luna-base-alpha-001',
  name: 'Luna Base Alpha',
  description: 'A modular lunar surface habitat designed for 4-person crew on 180-day exploration missions',
  version: '1.0.0',
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date('2024-01-20'),
  author: 'NASA Habitat Design Team',
  
  dimensions: {
    shape: HabitatShape.CYLINDER,
    radius: 4.0,
    height: 12.0,
  },
  
  missionParameters: {
    crewSize: 4,
    duration: 180,
    destination: Destination.LUNAR_SURFACE,
    launchVehicle: LaunchVehicle.SLS_BLOCK_1,
    missionType: 'exploration',
    emergencyEvacuation: true,
  },
  
  modules: [
    {
      id: 'command-center-001',
      type: ModuleType.COMMAND,
      name: 'Command Center',
      description: 'Primary command and control center with communications',
      position: { x: 0, y: 2, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 4, width: 3, height: 2.5 },
      volume: 30,
      mass: 15000,
      powerRequirement: 8,
      crewCapacity: 4,
      essential: true,
      adjacencyRequirements: ['crew-quarters-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'crew-quarters-001',
      type: ModuleType.HABITATION,
      name: 'Crew Quarters',
      description: 'Private crew quarters with sleeping and personal storage',
      position: { x: -5, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 6, width: 4, height: 2.5 },
      volume: 60,
      mass: 25000,
      powerRequirement: 5,
      crewCapacity: 4,
      essential: true,
      adjacencyRequirements: ['command-center-001'],
      adjacencyRestrictions: ['airlock-001'],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: false,
      },
    },
    {
      id: 'laboratory-001',
      type: ModuleType.LABORATORY,
      name: 'Science Laboratory',
      description: 'Multi-purpose laboratory for lunar samples and experiments',
      position: { x: 5, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 5, width: 3, height: 2.5 },
      volume: 37.5,
      mass: 20000,
      powerRequirement: 12,
      crewCapacity: 2,
      essential: true,
      adjacencyRequirements: ['command-center-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'airlock-001',
      type: ModuleType.AIRLOCK,
      name: 'Primary Airlock',
      description: 'Main EVA airlock for surface operations',
      position: { x: 0, y: -3, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 2.5, width: 2.5, height: 2.5 },
      volume: 15.6,
      mass: 8000,
      powerRequirement: 4,
      crewCapacity: 2,
      essential: true,
      adjacencyRequirements: [],
      adjacencyRestrictions: ['crew-quarters-001'],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'medical-bay-001',
      type: ModuleType.MEDICAL,
      name: 'Medical Bay',
      description: 'Medical treatment and health monitoring facility',
      position: { x: -2.5, y: -2, z: 3 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 3, width: 3, height: 2.5 },
      volume: 22.5,
      mass: 12000,
      powerRequirement: 6,
      crewCapacity: 1,
      essential: true,
      adjacencyRequirements: ['crew-quarters-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
  ],
  
  connections: [
    {
      id: 'conn-001',
      fromModuleId: 'command-center-001',
      toModuleId: 'crew-quarters-001',
      type: 'corridor',
      diameter: 1.0,
      length: 2.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'conn-002',
      fromModuleId: 'command-center-001',
      toModuleId: 'laboratory-001',
      type: 'corridor',
      diameter: 1.0,
      length: 2.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'conn-003',
      fromModuleId: 'command-center-001',
      toModuleId: 'airlock-001',
      type: 'hatch',
      diameter: 0.8,
      length: 1.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'conn-004',
      fromModuleId: 'crew-quarters-001',
      toModuleId: 'medical-bay-001',
      type: 'corridor',
      diameter: 0.8,
      length: 1.5,
      pressurized: true,
      bidirectional: true,
    },
  ],
  
  totalVolume: 603.2,
  pressurizedVolume: 603.2,
  netHabitableVolume: 422.2,
  totalMass: 80000,
  powerRequirement: 35,
  
  validationResults: [],
  complianceScore: 85,
};

// Sample 2: Mars Transit Habitat - Deep Space Transport
export const MARS_TRANSIT_HABITAT: HabitatDesign = {
  id: 'mars-transit-001',
  name: 'Mars Transit Habitat',
  description: 'Long-duration transport habitat for 6-person crew on 9-month journey to Mars',
  version: '1.2.0',
  createdAt: new Date('2024-02-01'),
  updatedAt: new Date('2024-02-15'),
  author: 'NASA Deep Space Habitat Team',
  
  dimensions: {
    shape: HabitatShape.TORUS,
    majorRadius: 15.0,
    minorRadius: 3.0,
  },
  
  missionParameters: {
    crewSize: 6,
    duration: 270,
    destination: Destination.MARS_ORBIT,
    launchVehicle: LaunchVehicle.STARSHIP,
    missionType: 'exploration',
    emergencyEvacuation: false,
  },
  
  modules: [
    {
      id: 'command-hub-001',
      type: ModuleType.COMMAND,
      name: 'Command Hub',
      description: 'Central command and navigation center',
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 5, width: 4, height: 3 },
      volume: 60,
      mass: 30000,
      powerRequirement: 15,
      crewCapacity: 6,
      essential: true,
      adjacencyRequirements: ['crew-hab-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'crew-hab-001',
      type: ModuleType.HABITATION,
      name: 'Crew Habitat Ring',
      description: 'Rotating habitat ring with artificial gravity',
      position: { x: 12, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 8, width: 5, height: 3 },
      volume: 120,
      mass: 45000,
      powerRequirement: 8,
      crewCapacity: 6,
      essential: true,
      adjacencyRequirements: ['command-hub-001', 'exercise-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: false,
      },
    },
    {
      id: 'exercise-001',
      type: ModuleType.EXERCISE,
      name: 'Exercise Module',
      description: 'Exercise equipment with artificial gravity',
      position: { x: -12, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 6, width: 4, height: 3 },
      volume: 72,
      mass: 25000,
      powerRequirement: 5,
      crewCapacity: 3,
      essential: false,
      adjacencyRequirements: ['crew-hab-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'greenhouse-001',
      type: ModuleType.GREENHOUSE,
      name: 'Agricultural Module',
      description: 'Food production and psychological benefits',
      position: { x: 0, y: 12, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 4, width: 4, height: 3 },
      volume: 48,
      mass: 18000,
      powerRequirement: 20,
      crewCapacity: 2,
      essential: false,
      adjacencyRequirements: [],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: false,
        equipmentAccess: true,
      },
    },
  ],
  
  connections: [
    {
      id: 'conn-hub-001',
      fromModuleId: 'command-hub-001',
      toModuleId: 'crew-hab-001',
      type: 'corridor',
      diameter: 1.2,
      length: 8.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'conn-hub-002',
      fromModuleId: 'command-hub-001',
      toModuleId: 'exercise-001',
      type: 'corridor',
      diameter: 1.2,
      length: 8.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'conn-hub-003',
      fromModuleId: 'command-hub-001',
      toModuleId: 'greenhouse-001',
      type: 'corridor',
      diameter: 1.0,
      length: 8.0,
      pressurized: true,
      bidirectional: true,
    },
  ],
  
  totalVolume: 2827.4,
  pressurizedVolume: 2827.4,
  netHabitableVolume: 2120.5,
  totalMass: 118000,
  powerRequirement: 48,
  
  validationResults: [],
  complianceScore: 92,
};

// Sample 3: ISS Gateway - LEO Research Station
export const ISS_GATEWAY: HabitatDesign = {
  id: 'iss-gateway-001',
  name: 'ISS Gateway',
  description: 'Low Earth Orbit research station for 8-person crew with rotating assignments',
  version: '2.1.0',
  createdAt: new Date('2024-03-01'),
  updatedAt: new Date('2024-03-10'),
  author: 'International Space Station Consortium',
  
  dimensions: {
    shape: HabitatShape.MODULAR,
    length: 20.0,
    width: 15.0,
    height: 8.0,
  },
  
  missionParameters: {
    crewSize: 8,
    duration: 90,
    destination: Destination.LEO,
    launchVehicle: LaunchVehicle.FALCON_HEAVY,
    missionType: 'research',
    emergencyEvacuation: true,
  },
  
  modules: [
    {
      id: 'core-module-001',
      type: ModuleType.COMMAND,
      name: 'Core Module',
      description: 'Central command and docking node',
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 6, width: 4, height: 3 },
      volume: 72,
      mass: 35000,
      powerRequirement: 12,
      crewCapacity: 8,
      essential: true,
      adjacencyRequirements: [],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'research-lab-001',
      type: ModuleType.LABORATORY,
      name: 'Primary Research Lab',
      description: 'Microgravity research and experimentation',
      position: { x: 8, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 8, width: 4, height: 3 },
      volume: 96,
      mass: 40000,
      powerRequirement: 18,
      crewCapacity: 4,
      essential: true,
      adjacencyRequirements: ['core-module-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: true,
      },
    },
    {
      id: 'crew-quarters-002',
      type: ModuleType.HABITATION,
      name: 'Crew Quarters A',
      description: 'Crew quarters for 4 astronauts',
      position: { x: 0, y: 6, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 6, width: 3, height: 3 },
      volume: 54,
      mass: 25000,
      powerRequirement: 6,
      crewCapacity: 4,
      essential: true,
      adjacencyRequirements: ['core-module-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: false,
      },
    },
    {
      id: 'crew-quarters-003',
      type: ModuleType.HABITATION,
      name: 'Crew Quarters B',
      description: 'Additional crew quarters for 4 astronauts',
      position: { x: 0, y: -6, z: 0 },
      rotation: { x: 0, y: 0, z: 0, w: 1 },
      dimensions: { length: 6, width: 3, height: 3 },
      volume: 54,
      mass: 25000,
      powerRequirement: 6,
      crewCapacity: 4,
      essential: true,
      adjacencyRequirements: ['core-module-001'],
      adjacencyRestrictions: [],
      accessRequirements: {
        directAccess: true,
        emergencyAccess: true,
        equipmentAccess: false,
      },
    },
  ],
  
  connections: [
    {
      id: 'core-lab-001',
      fromModuleId: 'core-module-001',
      toModuleId: 'research-lab-001',
      type: 'hatch',
      diameter: 1.0,
      length: 1.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'core-crew-a-001',
      fromModuleId: 'core-module-001',
      toModuleId: 'crew-quarters-002',
      type: 'hatch',
      diameter: 0.8,
      length: 1.0,
      pressurized: true,
      bidirectional: true,
    },
    {
      id: 'core-crew-b-001',
      fromModuleId: 'core-module-001',
      toModuleId: 'crew-quarters-003',
      type: 'hatch',
      diameter: 0.8,
      length: 1.0,
      pressurized: true,
      bidirectional: true,
    },
  ],
  
  totalVolume: 2400.0,
  pressurizedVolume: 276.0,
  netHabitableVolume: 193.2,
  totalMass: 125000,
  powerRequirement: 42,
  
  validationResults: [],
  complianceScore: 78,
};

export const SAMPLE_DESIGNS = [
  LUNA_BASE_ALPHA,
  MARS_TRANSIT_HABITAT,
  ISS_GATEWAY,
];

export default SAMPLE_DESIGNS;